In [110]:
# From https://machinelearningmastery.com/binary-classification-tutorial-with-the-keras-deep-learning-library/
import pandas
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.regularizers import L1L2
from sklearn.preprocessing import MinMaxScaler

In [116]:
# load dataset
dataframe = pandas.read_csv("/data/coinapi.csv")
dataset = dataframe.values
# split into input (X) and output (Y) variables
x = dataset[30000:-100,1:-1].astype(float)
y = dataset[30000:-100,-1:].astype(float)

scaler = MinMaxScaler(feature_range=(0, 1))
x_scaled = scaler.fit_transform(x)

x_train = np.array(x_scaled[:-200,:])
y_train = np.array(y[:-200,:])
x_val = np.array(x_scaled[-200:,:])
y_val = np.array(y[-200:,:])

In [131]:
print(x_train.shape, y_train.shape, x_val.shape, y_val.shape)
print(x_val, y_val)

(16034, 5) (16034, 1) (200, 5) (200, 1)
[[0.96280625 0.96638015 0.96405172 0.96724624 0.02474742]
 [0.96582455 0.96606775 0.96355092 0.97137411 0.01661583]
 [0.96577237 0.9646703  0.96343687 0.97100901 0.02071144]
 [0.96488485 0.96369656 0.96232366 0.96708832 0.00839341]
 [0.96315347 0.95832417 0.96054663 0.96339874 0.0093457 ]
 [0.95845146 0.96064404 0.95798664 0.96462523 0.01027901]
 [0.96129858 0.96331493 0.9626366  0.9694239  0.0093384 ]
 [0.96300578 0.95915822 0.96205043 0.96628476 0.0057461 ]
 [0.95931462 0.95832608 0.95612809 0.96469597 0.00651288]
 [0.95824132 0.95667032 0.95647636 0.96369327 0.01055306]
 [0.9566672  0.95238958 0.95327948 0.95473336 0.01415148]
 [0.95238615 0.94924765 0.9509719  0.95592002 0.00622871]
 [0.94911875 0.95089211 0.94963025 0.95382341 0.00840579]
 [0.95088857 0.95214171 0.95033711 0.9576323  0.00906378]
 [0.95202468 0.95480391 0.95521744 0.95975948 0.00482087]
 [0.95417459 0.96236068 0.95929855 0.96258749 0.00336425]
 [0.96118221 0.95900376 0.958203

In [127]:
model = Sequential()

In [128]:
model.add(Dense(20, activation='sigmoid', input_dim=5))
model.add(Dense(20, activation='sigmoid', input_dim=20))
model.add(Dense(20, activation='sigmoid', input_dim=20))
model.add(Dense(1, activation='softmax', input_dim=20))

In [129]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [130]:
model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val))

Epoch 1/100
502/502 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5122 - val_loss: 0.0000e+00 - val_accuracy: 0.4450
Epoch 2/100
502/502 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5122 - val_loss: 0.0000e+00 - val_accuracy: 0.4450
Epoch 3/100
502/502 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5122 - val_loss: 0.0000e+00 - val_accuracy: 0.4450
Epoch 4/100
502/502 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.5122 - val_loss: 0.0000e+00 - val_accuracy: 0.4450
Epoch 5/100
502/502 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5122 - val_loss: 0.0000e+00 - val_accuracy: 0.4450
Epoch 6/100
502/502 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5122 - val_loss: 0.0000e+00 - val_accuracy: 0.4450
Epoch 7/100
502/502 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accura

KeyboardInterrupt: 